name: cli-chatbot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - openai
      - anthropic
      - google-generativeai
      - groq
      - rich
      - typer
      - prompt-toolkit
      - pytest
      - pytest-asyncio
      - python-dotenv

